version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/email-mvt-archive'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7

  - package-ecosystem: 'npm'
    directory: '/cdk'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
