Parameters:
  Stack:
    Type: String
    Default: targeting
  Stage:
    Type: String
    Default: CODE
    AllowedValues:
      - CODE
      - PROD
  StageSubdomain:
    Type: String
    Default: email
  HostedZoneID:
    Type: String
  TopLevelDomainTLD:
    Type: String
    Default: targeting.guardianapis.com
  CloudFrontACMCertificateARN:
    Type: String
Resources:
  EmailMVTPixelOriginAccessIdentity20CDA542:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment:
          Fn::Join:
            - ""
            - - "Access Identity for "
              - Ref: StageSubdomain
              - "."
              - Ref: TopLevelDomainTLD
    Metadata:
      aws:cdk:path: EmailMVTPixel/EmailMVTPixel/OriginAccessIdentity/Resource
  EmailMVTPixelSourceS3BucketD4E04505:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
          - ""
          - - source-
            - Ref: StageSubdomain
            - "."
            - Ref: TopLevelDomainTLD
      Tags:
        - Key: App
          Value: EmailMVTPixel
        - Key: Stack
          Value:
            Ref: Stack
        - Key: Stage
          Value:
            Ref: Stage
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: EmailMVTPixel/EmailMVTPixel/SourceS3Bucket/Resource
  EmailMVTPixelSourceS3BucketPolicy0376DD9D:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: EmailMVTPixelSourceS3BucketD4E04505
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - EmailMVTPixelOriginAccessIdentity20CDA542
                  - S3CanonicalUserId
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - EmailMVTPixelSourceS3BucketD4E04505
                      - Arn
                  - /*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - EmailMVTPixelOriginAccessIdentity20CDA542
                  - S3CanonicalUserId
            Resource:
              - Fn::GetAtt:
                  - EmailMVTPixelSourceS3BucketD4E04505
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - EmailMVTPixelSourceS3BucketD4E04505
                        - Arn
                    - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: EmailMVTPixel/EmailMVTPixel/SourceS3Bucket/Policy/Resource
  EmailMVTPixelLogsS3BucketA1CB2D8A:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName:
        Fn::Join:
          - ""
          - - logs-
            - Ref: StageSubdomain
            - "."
            - Ref: TopLevelDomainTLD
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 2
            ExpirationInDays: 28
            Status: Enabled
      Tags:
        - Key: App
          Value: EmailMVTPixel
        - Key: Stack
          Value:
            Ref: Stack
        - Key: Stage
          Value:
            Ref: Stage
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: EmailMVTPixel/EmailMVTPixel/LogsS3Bucket/Resource
  EmailMVTPixelCloudFrontDistributionCFDistributionE7DEDC70:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - Fn::Join:
              - ""
              - - Ref: StageSubdomain
                - "."
                - Ref: TopLevelDomainTLD
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: origin1
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Logging:
          Bucket:
            Fn::GetAtt:
              - EmailMVTPixelLogsS3BucketA1CB2D8A
              - RegionalDomainName
          IncludeCookies: false
        Origins:
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            DomainName:
              Fn::GetAtt:
                - EmailMVTPixelSourceS3BucketD4E04505
                - RegionalDomainName
            Id: origin1
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - origin-access-identity/cloudfront/
                    - Ref: EmailMVTPixelOriginAccessIdentity20CDA542
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn:
            Ref: CloudFrontACMCertificateARN
          SslSupportMethod: sni-only
      Tags:
        - Key: App
          Value: EmailMVTPixel
        - Key: Stack
          Value:
            Ref: Stack
        - Key: Stage
          Value:
            Ref: Stage
    Metadata:
      aws:cdk:path: EmailMVTPixel/EmailMVTPixel/CloudFrontDistribution/CFDistribution
  EmailMVTPixelRoute53AAARecordAlias6676FDD1:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        Fn::Join:
          - ""
          - - Ref: StageSubdomain
            - "."
            - Ref: TopLevelDomainTLD
            - "."
      Type: AAAA
      AliasTarget:
        DNSName:
          Fn::GetAtt:
            - EmailMVTPixelCloudFrontDistributionCFDistributionE7DEDC70
            - DomainName
        HostedZoneId:
          Fn::FindInMap:
            - AWSCloudFrontPartitionHostedZoneIdMap
            - Ref: AWS::Partition
            - zoneId
      HostedZoneId:
        Ref: HostedZoneID
    Metadata:
      aws:cdk:path: EmailMVTPixel/EmailMVTPixel/Route53AAARecordAlias/Resource
  EmailMVTPixelRoute53ARecord8678A062:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        Fn::Join:
          - ""
          - - Ref: StageSubdomain
            - "."
            - Ref: TopLevelDomainTLD
            - "."
      Type: A
      AliasTarget:
        DNSName:
          Fn::GetAtt:
            - EmailMVTPixelCloudFrontDistributionCFDistributionE7DEDC70
            - DomainName
        HostedZoneId:
          Fn::FindInMap:
            - AWSCloudFrontPartitionHostedZoneIdMap
            - Ref: AWS::Partition
            - zoneId
      HostedZoneId:
        Ref: HostedZoneID
    Metadata:
      aws:cdk:path: EmailMVTPixel/EmailMVTPixel/Route53ARecord/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.75.0,@aws-cdk/assets=1.75.0,@aws-cdk/aws-applicationautoscaling=1.75.0,@aws-cdk/aws-autoscaling-common=1.75.0,@aws-cdk/aws-certificatemanager=1.75.0,@aws-cdk/aws-cloudfront=1.75.0,@aws-cdk/aws-cloudwatch=1.75.0,@aws-cdk/aws-codeguruprofiler=1.75.0,@aws-cdk/aws-ec2=1.75.0,@aws-cdk/aws-events=1.75.0,@aws-cdk/aws-iam=1.75.0,@aws-cdk/aws-kms=1.75.0,@aws-cdk/aws-lambda=1.75.0,@aws-cdk/aws-logs=1.75.0,@aws-cdk/aws-route53=1.75.0,@aws-cdk/aws-route53-targets=1.75.0,@aws-cdk/aws-s3=1.75.0,@aws-cdk/aws-s3-assets=1.75.0,@aws-cdk/aws-sqs=1.75.0,@aws-cdk/aws-ssm=1.75.0,@aws-cdk/cloud-assembly-schema=1.75.0,@aws-cdk/core=1.75.0,@aws-cdk/cx-api=1.75.0,@aws-cdk/region-info=1.75.0,jsii-runtime=node.js/v12.14.1
    Metadata:
      aws:cdk:path: EmailMVTPixel/CDKMetadata/Default
Mappings:
  AWSCloudFrontPartitionHostedZoneIdMap:
    aws:
      zoneId: Z2FDTNDATAQYW2
    aws-cn:
      zoneId: Z3RFFRIM2A3IF5
Outputs:
  EmailMVTPixelCFLogsS3BucketOutput:
    Value:
      Ref: EmailMVTPixelLogsS3BucketA1CB2D8A
    Export:
      Name:
        Fn::Join:
          - ""
          - - EmailMVTPixel-Logs-S3Bucket-
            - Ref: Stage

