Parameters:
  Stage:
    Type: String
    Default: CODE
    AllowedValues:
      - CODE
      - PROD
  DestinationBucket:
    Type: String
    Description: S3 bucket to copy logs into. Make sure the Lambda has write access into the bucket and that it's encrypted, has versioning disabled, and has a 28 day retention policy.
Resources:
  EmailMVTLogArchiverServiceRole3E0B7412:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - lambda.
                    - Ref: AWS::URLSuffix
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: EmailMVTLogArchiverStack/EmailMVTLogArchiver/Archiver/ServiceRole/Resource
  EmailMVTLogArchiverServiceRoleDefaultPolicy2B34FF4D:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: logs:CreateLogGroup
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - arn:aws:logs:*:*:log-group:/aws/lambda/EmailMVTLogArchiver-
                  - Ref: Stage
                  - :*
          - Action:
              - s3:GetObject
              - s3:ListBucket
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Fn::ImportValue:
                        Fn::Join:
                          - ""
                          - - EmailMVTPixel-Logs-S3Bucket-
                            - Ref: Stage
              - Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Fn::ImportValue:
                        Fn::Join:
                          - ""
                          - - EmailMVTPixel-Logs-S3Bucket-
                            - Ref: Stage
                    - /*
          - Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectAcl
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: DestinationBucket
                  - /*
        Version: "2012-10-17"
      PolicyName: EmailMVTLogArchiverServiceRoleDefaultPolicy2B34FF4D
      Roles:
        - Ref: EmailMVTLogArchiverServiceRole3E0B7412
    Metadata:
      aws:cdk:path: EmailMVTLogArchiverStack/EmailMVTLogArchiver/Archiver/ServiceRole/DefaultPolicy/Resource
  EmailMVTLogArchiver1564C123:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: >
          const aws = require('aws-sdk');

          const s3 = new aws.S3();

          const filenameDateRegex = /(\d\d\d\d-\d\d-\d\d)-\d\d/;


          async function listAllObjects(s3Objects, Bucket, ContinuationToken){
            const { Contents, IsTruncated, NextContinuationToken } = await s3.listObjectsV2({ Bucket, ContinuationToken }).promise();
            s3Objects.push(...Contents);
            if (IsTruncated) {
              await listAllObjects(s3Objects, Bucket, NextContinuationToken); // RECURSIVE CALL
            }
          }


          exports.handler = async () => {
            const allObjects = [];
            await listAllObjects(allObjects, process.env.source_s3_bucket);
            const objectsWithDesiredFolder = allObjects
              .filter(s3object => filenameDateRegex.test(s3object.Key))
              .map(s3object => {
                const dateFromFilename = s3object.Key.match(filenameDateRegex)[1];
                return [s3object.Key, dateFromFilename];
              });
            const promises = objectsWithDesiredFolder.map(tuple => {
              const [source, destinationFolder] = tuple;
              return s3.headObject({
                Bucket: `${process.env.destination_s3_bucket}/dt=${destinationFolder}`,
                Key: source
              }).promise()
                .then(() => Promise.resolve('skipped'))
                .catch(() => s3.copyObject({
                  ACL: 'bucket-owner-read',
                  Bucket: `${process.env.destination_s3_bucket}/dt=${destinationFolder}`,
                  CopySource: `${process.env.source_s3_bucket}/${source}`,
                  Key: source
                }).promise());
            });
            const results = await Promise.all(promises);
            const copiedResults = results.filter(value => value !== 'skipped');
            const skippedResults = results.filter(value => value === 'skipped')
            const log = `Copied ${copiedResults.length} objects. Skipped ${skippedResults.length} objects.`
            console.log(log);
            return log;
          };
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - EmailMVTLogArchiverServiceRole3E0B7412
          - Arn
      Runtime: nodejs8.10
      Environment:
        Variables:
          source_s3_bucket:
            Fn::ImportValue:
              Fn::Join:
                - ""
                - - EmailMVTPixel-Logs-S3Bucket-
                  - Ref: Stage
          destination_s3_bucket:
            Ref: DestinationBucket
      FunctionName:
        Fn::Join:
          - ""
          - - EmailMVTLogArchiver-
            - Ref: Stage
      MemorySize: 512
      Timeout: 60
    DependsOn:
      - EmailMVTLogArchiverServiceRoleDefaultPolicy2B34FF4D
      - EmailMVTLogArchiverServiceRole3E0B7412
    Metadata:
      aws:cdk:path: EmailMVTLogArchiverStack/EmailMVTLogArchiver/Archiver/Resource
  EmailMVTLogArchiverAllowEventRuleEmailMVTLogArchiverStackEmailMVTLogArchiverRuleD2670257804EEBEC:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - EmailMVTLogArchiver1564C123
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - EmailMVTLogArchiverRuleED22675D
          - Arn
    Metadata:
      aws:cdk:path: EmailMVTLogArchiverStack/EmailMVTLogArchiver/Archiver/AllowEventRuleEmailMVTLogArchiverStackEmailMVTLogArchiverRuleD2670257
  EmailMVTLogArchiverRuleED22675D:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 1 ? * * *)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - EmailMVTLogArchiver1564C123
              - Arn
          Id: Target0
    Metadata:
      aws:cdk:path: EmailMVTLogArchiverStack/EmailMVTLogArchiver/Rule/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.4.0,@aws-cdk/assets=1.4.0,@aws-cdk/aws-applicationautoscaling=1.4.0,@aws-cdk/aws-autoscaling=1.4.0,@aws-cdk/aws-autoscaling-common=1.4.0,@aws-cdk/aws-autoscaling-hooktargets=1.4.0,@aws-cdk/aws-cloudformation=1.4.0,@aws-cdk/aws-cloudfront=1.4.0,@aws-cdk/aws-cloudwatch=1.4.0,@aws-cdk/aws-ec2=1.4.0,@aws-cdk/aws-ecr=1.4.0,@aws-cdk/aws-ecr-assets=1.4.0,@aws-cdk/aws-ecs=1.4.0,@aws-cdk/aws-elasticloadbalancingv2=1.4.0,@aws-cdk/aws-events=1.4.0,@aws-cdk/aws-events-targets=1.4.0,@aws-cdk/aws-iam=1.4.0,@aws-cdk/aws-kms=1.4.0,@aws-cdk/aws-lambda=1.4.0,@aws-cdk/aws-logs=1.4.0,@aws-cdk/aws-route53=1.4.0,@aws-cdk/aws-route53-targets=1.4.0,@aws-cdk/aws-s3=1.4.0,@aws-cdk/aws-s3-assets=1.4.0,@aws-cdk/aws-servicediscovery=1.4.0,@aws-cdk/aws-sns=1.4.0,@aws-cdk/aws-sns-subscriptions=1.4.0,@aws-cdk/aws-sqs=1.4.0,@aws-cdk/aws-ssm=1.4.0,@aws-cdk/core=1.4.0,@aws-cdk/custom-resources=1.4.0,@aws-cdk/cx-api=1.4.0,@aws-cdk/region-info=1.4.0,jsii-runtime=node.js/v8.11.1

